//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackQuestionResponse
    {
        public int Id { get; set; }
        public string MeetupSessionId { get; set; }
        public int FeedbackQuestionId { get; set; }
        public Nullable<short> Rating { get; set; }
        public string FeedbackWriteup { get; set; }
        public string AdditionalDetails { get; set; }
    
        public virtual FeedbackQuestionAndMeetupSession FeedbackQuestionAndMeetupSession { get; set; }
    }
}
