//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackQuestionAndMeetupSession
    {
        public FeedbackQuestionAndMeetupSession()
        {
            this.FeedbackQuestionResponses = new HashSet<FeedbackQuestionResponse>();
        }
    
        public string MeetupSessionId { get; set; }
        public int FeedbackQuestionId { get; set; }
    
        public virtual FeedbackQuestion FeedbackQuestion { get; set; }
        public virtual ICollection<FeedbackQuestionResponse> FeedbackQuestionResponses { get; set; }
    }
}
