//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetupSession
    {
        public MeetupSession()
        {
            this.FeedbackQuestions = new HashSet<FeedbackQuestion>();
        }
    
        public int Id { get; set; }
        public string SessionTitle { get; set; }
        public string MeetupIdentifier { get; set; }
        public string AdditionalDetails { get; set; }
    
        public virtual ICollection<FeedbackQuestion> FeedbackQuestions { get; set; }
    }
}
