//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Herd.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuthUser
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string AdditionalData { get; set; }
        public System.DateTime DataTimeKeyObtained { get; set; }
        public string UserName { get; set; }
    }
}
